# Generated by Django 2.2.5 on 2021-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('周期', models.TextField(blank=True, null=True)),
                ('员工编号', models.TextField(blank=True, null=True)),
                ('平时加班时数', models.FloatField(blank=True, null=True)),
                ('周末加班时数', models.FloatField(blank=True, null=True)),
                ('节日加班时数', models.FloatField(blank=True, null=True)),
                ('有薪假时数', models.FloatField(blank=True, null=True)),
                ('法定假时数', models.FloatField(blank=True, null=True)),
                ('基本工资', models.FloatField(blank=True, null=True)),
                ('平均时薪', models.FloatField(blank=True, null=True)),
                ('法定日平均工资', models.FloatField(blank=True, null=True)),
                ('平时加班费', models.FloatField(blank=True, null=True)),
                ('公休日加班费', models.FloatField(blank=True, null=True)),
                ('节日加班费', models.FloatField(blank=True, null=True)),
                ('有薪假工资', models.FloatField(blank=True, null=True)),
                ('法定假工资', models.FloatField(blank=True, null=True)),
                ('最低工资补助', models.FloatField(blank=True, null=True)),
                ('计件工资', models.FloatField(blank=True, null=True)),
                ('全勤奖', models.FloatField(blank=True, null=True)),
                ('应发工资', models.FloatField(blank=True, null=True)),
                ('工龄奖', models.FloatField(blank=True, null=True)),
                ('公积金', models.FloatField(blank=True, null=True)),
                ('社保', models.FloatField(blank=True, null=True)),
                ('实发工资', models.FloatField(blank=True, null=True)),
                ('个税', models.FloatField(blank=True, null=True)),
                ('保健补助', models.FloatField(blank=True, null=True)),
                ('应税额', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '部门工资',
                'verbose_name_plural': '部门工资',
                'managed': False,
            },
        ),
    ]
