# Generated by Django 2.2.5 on 2021-07-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysarly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salary01',
            table='mysqrly01',
        ),
    ]
