# Generated by Django 2.2.5 on 2021-07-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysarly', '0003_auto_20210714_1113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salary01',
            table='salary01',
        ),
    ]
